import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "fr" | "nl" | "de";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    "nav.buy": "Acheter",
    "nav.sell": "Vendre",
    "nav.favorites": "Favoris",
    "nav.compare": "Comparer",
    "nav.messages": "Messages",
    "nav.dashboard": "Dashboard",
    "nav.settings": "Paramètres",
    "nav.faq": "FAQ",
    "nav.login": "Connexion",
    "nav.logout": "Déconnexion",
    "nav.language": "Langue",
    "theme.light": "Mode clair",
    "theme.dark": "Mode sombre",
    "logout.success": "Déconnexion",
    "logout.description": "Vous avez été déconnecté avec succès",
    
    // Hero
    "hero.badge": "Marché automobile belge",
    "hero.title1": "Trouvez votre prochaine",
    "hero.title2": "voiture en Belgique",
    "hero.subtitle": "Des milliers de véhicules vérifiés, avec Car-Pass et compatibilité LEZ garantie",
    "hero.search": "Rechercher",
    "hero.vehicles": "Véhicules",
    "hero.verified": "Car-Pass vérifié",
    "hero.brands": "Marques",
    
    // Brands
    "brands.title": "Marques populaires en Belgique",
    
    // Filters
    "filters.title": "Filtres",
    "filters.vehicles": "véhicules",
    "filters.brand": "Marque",
    "filters.allBrands": "Toutes les marques",
    "filters.model": "Modèle",
    "filters.budget": "Budget",
    "filters.year": "Année",
    "filters.mileage": "Kilométrage",
    "filters.fuel": "Carburant",
    "filters.transmission": "Boîte de vitesse",
    "filters.euroNorm": "Norme Euro (LEZ)",
    "filters.lezOnly": "Compatible LEZ uniquement",
    "filters.reset": "Réinitialiser les filtres",
    "filters.allModels": "Tous les modèles",
    "filters.selectBrandFirst": "Sélectionnez d'abord une marque",
    "filters.gasoline": "Essence",
    "filters.diesel": "Diesel",
    "filters.hybrid": "Hybride",
    "filters.electric": "Électrique",
    "filters.manual": "Manuelle",
    "filters.automatic": "Automatique",
    
    // Car Card & Detail
    "car.addCompare": "Ajouter au comparateur",
    "car.removeCompare": "Retirer du comparateur",
    "car.addedCompare": "Ajouté au comparateur",
    "car.removedCompare": "Retiré du comparateur",
    "car.maxCompare": "Maximum 3 véhicules dans le comparateur",
    "car.notFound": "Véhicule non trouvé",
    "car.notFoundDesc": "Ce véhicule n'existe pas ou a été retiré de la vente.",
    "car.backToListings": "Retour aux annonces",
    "car.backToResults": "Retour aux résultats",
    "car.specifications": "Caractéristiques",
    "car.description": "Description",
    "car.sendMessage": "Envoyer un message",
    "car.callSeller": "Appeler le vendeur",
    "car.sendEmail": "Envoyer un email",
    "car.linkCopied": "Lien copié !",
    "car.linkCopiedDesc": "Le lien a été copié dans le presse-papier",
    "car.relatedCars": "Véhicules similaires",
    "car.location": "Localisation",
    "car.disclaimer": "AutoRa n'est pas intermédiaire de paiement. Ne payez jamais avant d'avoir vu le véhicule.",
    
    // Auth
    "auth.login": "Connexion",
    "auth.signup": "Créer un compte",
    "auth.loginSubtitle": "Connectez-vous pour accéder à votre espace",
    "auth.signupSubtitle": "Inscrivez-vous pour commencer",
    "auth.continueGoogle": "Continuer avec Google",
    "auth.or": "ou",
    "auth.fullName": "Nom complet",
    "auth.email": "Adresse email",
    "auth.password": "Mot de passe",
    "auth.submit": "Se connecter",
    "auth.submitSignup": "S'inscrire",
    "auth.loading": "Chargement...",
    "auth.noAccount": "Pas encore de compte ?",
    "auth.hasAccount": "Déjà un compte ?",
    "auth.backHome": "Retour à l'accueil",
    "auth.findIdealCar": "Trouvez votre voiture idéale",
    "auth.heroDesc": "Des milliers de véhicules vérifiés avec Car-Pass et compatibilité LEZ garantie sur le marché belge.",
    "auth.errorLogin": "Erreur de connexion",
    "auth.errorCredentials": "Email ou mot de passe incorrect",
    "auth.welcome": "Bienvenue !",
    "auth.loginSuccess": "Connexion réussie",
    "auth.accountExists": "Compte existant",
    "auth.accountExistsDesc": "Un compte existe déjà avec cette adresse email",
    "auth.accountCreated": "Compte créé !",
    "auth.accountCreatedDesc": "Votre compte a été créé avec succès",
    "auth.error": "Erreur",
    "auth.unexpectedError": "Une erreur inattendue s'est produite",
    "auth.invalidEmail": "Adresse email invalide",
    "auth.passwordMin": "Le mot de passe doit contenir au moins 6 caractères",
    "auth.passwordMinStrong": "Le mot de passe doit contenir au moins 8 caractères",
    "auth.passwordUppercase": "Le mot de passe doit contenir au moins une majuscule",
    "auth.passwordLowercase": "Le mot de passe doit contenir au moins une minuscule",
    "auth.passwordNumber": "Le mot de passe doit contenir au moins un chiffre",
    "auth.passwordSpecial": "Le mot de passe doit contenir au moins un caractère spécial",
    "auth.nameMin": "Le nom doit contenir au moins 2 caractères",
    "auth.forgotPassword": "Mot de passe oublié",
    "auth.forgotPasswordDesc": "Entrez votre adresse email et nous vous enverrons un lien pour réinitialiser votre mot de passe.",
    "auth.forgotPasswordLink": "Mot de passe oublié ?",
    "auth.sendResetLink": "Envoyer le lien",
    "auth.resetEmailSent": "Email envoyé !",
    "auth.resetEmailSentDesc": "Consultez votre boîte de réception pour réinitialiser votre mot de passe.",
    "auth.backToLogin": "Retour à la connexion",
    "auth.newPassword": "Nouveau mot de passe",
    "auth.newPasswordDesc": "Choisissez un nouveau mot de passe sécurisé pour votre compte.",
    "auth.newPasswordPlaceholder": "Nouveau mot de passe",
    "auth.confirmPasswordPlaceholder": "Confirmer le mot de passe",
    "auth.passwordsNotMatch": "Les mots de passe ne correspondent pas",
    "auth.resetPasswordSubmit": "Réinitialiser le mot de passe",
    "auth.passwordResetSuccess": "Mot de passe réinitialisé !",
    "auth.passwordResetSuccessDesc": "Votre mot de passe a été modifié avec succès.",
    "auth.goToHome": "Aller à l'accueil",
    "auth.resetLinkExpired": "Le lien de réinitialisation a expiré ou est invalide.",
    "auth.verificationEmailSent": "Vérifiez votre email",
    "auth.verificationEmailSentDesc": "Nous avons envoyé un email de vérification à votre adresse. Cliquez sur le lien pour activer votre compte.",
    "auth.checkSpam": "Vérifiez également votre dossier spam si vous ne trouvez pas l'email.",
    "auth.emailNotVerified": "Email non vérifié",
    "auth.emailNotVerifiedDesc": "Veuillez vérifier votre email avant de vous connecter.",
    "auth.resendEmail": "Renvoyer l'email de vérification",
    "auth.resendSuccess": "Email envoyé !",
    "auth.resendSuccessDesc": "Un nouvel email de vérification a été envoyé.",
    
    // Sell Car
    "sell.title": "Vendez votre voiture",
    "sell.editTitle": "Modifier votre annonce",
    "sell.subtitle": "Publiez votre annonce en quelques minutes et touchez des milliers d'acheteurs en Belgique",
    "sell.editSubtitle": "Mettez à jour les informations de votre véhicule",
    "sell.loginToSell": "Connectez-vous pour vendre",
    "sell.loginDesc": "Créez un compte gratuit pour publier votre annonce et gérer vos véhicules.",
    "sell.secureListings": "Annonces sécurisées",
    "sell.quickPublish": "Publication rapide",
    "sell.carpassVerification": "Vérification Car-Pass",
    "sell.loginSignup": "Se connecter / S'inscrire",
    
    // FAQ
    "faq.helpCenter": "Centre d'aide",
    "faq.title": "Questions fréquentes",
    "faq.subtitle": "Trouvez rapidement les réponses à vos questions sur AutoRa, le Car-Pass, les zones LEZ et bien plus encore.",
    "faq.searchPlaceholder": "Rechercher une question...",
    "faq.all": "Toutes",
    "faq.buying": "Acheter une voiture",
    "faq.selling": "Vendre sur AutoRa",
    "faq.lezCarpass": "LEZ & Car-Pass",
    "faq.securityPrivacy": "Sécurité & Confidentialité",
    "faq.account": "Compte",
    "faq.purchase": "Achat",
    "faq.sale": "Vente",
    "faq.security": "Sécurité",
    "faq.payment": "Paiement",
    "faq.noResults": "Aucune question ne correspond à votre recherche.",
    "faq.resultsFor": "résultats trouvés",
    "faq.resultFor": "résultat trouvé",
    "faq.noResult": "Aucun résultat",
    "faq.for": "pour",
    "faq.in": "dans",
    "faq.notFound": "Vous n'avez pas trouvé votre réponse ?",
    "faq.notFoundDesc": "Notre équipe est là pour vous aider. Contactez-nous par email à contact@autora.be",
    "faq.contactUs": "Nous contacter",
    "faq.linkCopied": "Lien copié !",
    
    // Footer
    "footer.description": "La marketplace automobile belge de confiance. Tous nos véhicules sont vérifiés avec Car-Pass.",
    "footer.navigation": "Navigation",
    "footer.buyCar": "Acheter une voiture",
    "footer.sellCar": "Vendre ma voiture",
    "footer.estimate": "Estimer mon véhicule",
    "footer.lezGuide": "Guide LEZ Belgique",
    "footer.info": "Informations",
    "footer.about": "À propos de nous",
    "footer.carpass": "Car-Pass Belgique",
    "footer.terms": "Conditions générales",
    "footer.privacy": "Politique de confidentialité",
    "footer.legal": "Mentions légales",
    "footer.contact": "Contact",
    "footer.contactForm": "Formulaire de contact",
    "footer.rights": "Tous droits réservés.",
    "footer.madeWith": "Fait avec ❤️ en Belgique",
    "footer.slogan": "L'auto en toute confiance",
    "footer.tagline": "Trouvez votre prochaine voiture sur la première plateforme d'annonces automobiles dédiée au marché belge.",
    "footer.warning": "Attention",
    "footer.warningText": "Autora est une plateforme d'annonces. Nous ne sommes pas responsables de la transaction ou de l'état du véhicule. Ne versez jamais d'acompte sans avoir vu le vendeur en personne et vérifié le véhicule.",
    "footer.gdprTitle": "Protection des données (RGPD)",
    "footer.gdprText": "Vos données personnelles sont traitées conformément au règlement européen RGPD. Vous disposez d'un droit d'accès, de rectification et de suppression de vos données. Contactez-nous à contact@autora.be pour toute demande.",
    
    // Messages
    "messages.title": "Messages",
    "messages.noMessages": "Aucun message",
    "messages.noMessagesDesc": "Vous n'avez pas encore de conversations. Contactez un vendeur pour commencer.",
    "messages.viewVehicles": "Voir les véhicules",
    "messages.conversations": "Conversations",
    "messages.noMessage": "Aucun message",
    "messages.selectConversation": "Sélectionnez une conversation",
    "messages.yesterday": "Hier",
    
    // Settings
    "settings.title": "Paramètres",
    "settings.back": "Retour",
    "settings.notifications": "Notifications",
    "settings.notificationsDesc": "Gérez vos préférences de notifications",
    "settings.emailNotifications": "Notifications par email",
    "settings.emailNotificationsDesc": "Recevez un email quand un acheteur vous envoie un message",
    "settings.emailEnabled": "Notifications email activées",
    "settings.emailDisabled": "Notifications email désactivées",
    "settings.errorUpdate": "Erreur lors de la mise à jour des préférences",
    "settings.account": "Compte",
    "settings.accountDesc": "Informations de votre compte",
    "settings.email": "Email",
    
    // Dashboard
    "dashboard.sellerArea": "Espace vendeur",
    "dashboard.title": "Tableau de bord",
    "dashboard.subtitle": "Suivez les performances de vos annonces",
    "dashboard.exportCSV": "Exporter CSV",
    "dashboard.listings": "Annonces",
    "dashboard.totalViews": "Vues totales",
    "dashboard.messages": "Messages",
    "dashboard.favorites": "Favoris",
    "dashboard.globalPerformance": "Performance globale",
    "dashboard.noDataAvailable": "Aucune donnée disponible",
    "dashboard.detailByListing": "Détail par annonce",
    "dashboard.noListingsYet": "Vous n'avez pas encore d'annonces",
    "dashboard.createListing": "Créer une annonce",
    "dashboard.views": "Vues",
    "dashboard.published": "Publiée",
    "dashboard.pending": "En attente",
    "dashboard.rejected": "Refusée",
    "dashboard.deleteListing": "Supprimer cette annonce ?",
    "dashboard.deleteConfirm": "Êtes-vous sûr de vouloir supprimer l'annonce pour",
    "dashboard.deleteIrreversible": "Cette action est irréversible.",
    "dashboard.cancel": "Annuler",
    "dashboard.delete": "Supprimer",
    "dashboard.deleting": "Suppression...",
    "dashboard.deleteSuccess": "Annonce supprimée avec succès",
    "dashboard.deleteError": "Erreur lors de la suppression",
    "dashboard.csvDownloaded": "Export CSV téléchargé",
    "dashboard.vehicle": "Véhicule",
    "dashboard.status": "Statut",
    "dashboard.price": "Prix",
    "dashboard.createdAt": "Date de création",
    "dashboard.total": "TOTAL",
    "dashboard.viewStats": "Voir les statistiques",

    // Stats
    "stats.analytics": "Analytiques",
    "stats.title": "Statistiques détaillées",
    "stats.subtitle": "Analysez en profondeur les performances de vos annonces",
    "stats.backToDashboard": "Retour au tableau de bord",
    "stats.totalViews": "Vues totales",
    "stats.totalFavorites": "Favoris totaux",
    "stats.vsPrevious": "vs période précédente",
    "stats.evolution": "Évolution dans le temps",
    "stats.evolutionDesc": "Vues et favoris sur la période sélectionnée",
    "stats.views": "Vues",
    "stats.favorites": "Favoris",
    "stats.noData": "Aucune donnée disponible",
    "stats.viewsDistribution": "Répartition des vues",
    "stats.viewsDistributionDesc": "Distribution des vues par véhicule",
    "stats.performanceByVehicle": "Performance par véhicule",
    "stats.performanceByVehicleDesc": "Comparaison des vues et favoris",
    "stats.detailByVehicle": "Détail par véhicule",
    "stats.detailByVehicleDesc": "Classement de vos annonces par popularité",
    "stats.noListings": "Aucune annonce disponible",

    // Reviews
    "reviews.title": "Avis et notes",
    "reviews.review": "avis",
    "reviews.reviews": "avis",
    "reviews.leaveReview": "Laissez votre avis",
    "reviews.yourRating": "Votre note",
    "reviews.commentPlaceholder": "Partagez votre expérience (optionnel)...",
    "reviews.submit": "Publier l'avis",
    "reviews.submitting": "Publication...",
    "reviews.submitted": "Avis publié",
    "reviews.submittedDesc": "Merci pour votre avis !",
    "reviews.deleted": "Avis supprimé",
    "reviews.noReviews": "Aucun avis pour le moment. Soyez le premier à donner votre avis !",
    "reviews.loginRequired": "Connexion requise",
    "reviews.loginRequiredDesc": "Connectez-vous pour laisser un avis",
    "reviews.loginToReview": "Connectez-vous pour laisser un avis sur ce véhicule",
    "reviews.ratingRequired": "Veuillez sélectionner une note",
    "reviews.cannotReviewOwn": "Vous ne pouvez pas noter votre propre annonce",
    "reviews.error": "Erreur lors de la publication",
    
    // Cookie Consent
    "cookie.title": "Nous utilisons des cookies 🍪",
    "cookie.description": "AutoRa utilise des cookies pour améliorer votre expérience, analyser le trafic et personnaliser le contenu. Vous pouvez accepter tous les cookies, les refuser ou personnaliser vos préférences.",
    "cookie.acceptAll": "Tout accepter",
    "cookie.rejectAll": "Tout refuser",
    "cookie.customize": "Personnaliser",
    "cookie.settings": "Préférences cookies",
    "cookie.settingsDesc": "Gérez vos préférences de cookies",
    "cookie.essential": "Cookies essentiels",
    "cookie.essentialDesc": "Nécessaires au fonctionnement du site. Ils ne peuvent pas être désactivés.",
    "cookie.analytics": "Cookies analytiques",
    "cookie.analyticsDesc": "Nous aident à comprendre comment vous utilisez le site pour l'améliorer.",
    "cookie.personalization": "Cookies de personnalisation",
    "cookie.personalizationDesc": "Permettent de mémoriser vos préférences et d'afficher des recommandations pertinentes.",
    "cookie.alwaysActive": "Toujours actif",
    "cookie.savePreferences": "Enregistrer mes préférences",
    "cookie.moreInfo": "Pour plus d'informations, consultez notre",
    "cookie.privacyPolicy": "politique de confidentialité",
    
    // Contact
    "contact.title": "Contactez-nous",
    "contact.subtitle": "Une question ? Parlons-en",
    "contact.description": "Notre équipe est à votre disposition pour répondre à toutes vos questions concernant l'achat ou la vente de votre véhicule.",
    "contact.info": "Informations de contact",
    "contact.infoDesc": "Plusieurs moyens de nous joindre",
    "contact.email": "Email",
    "contact.phone": "Téléphone",
    "contact.address": "Adresse",
    "contact.hours": "Horaires",
    "contact.hoursValue": "Lun-Ven: 9h-18h | Sam: 10h-16h",
    "contact.fastResponse": "Réponse rapide",
    "contact.fastResponseDesc": "Nous répondons généralement sous 24 heures ouvrées.",
    "contact.formTitle": "Envoyez-nous un message",
    "contact.formDesc": "Remplissez le formulaire ci-dessous et nous vous répondrons rapidement",
    "contact.fullName": "Nom complet",
    "contact.subject": "Sujet",
    "contact.subjectPlaceholder": "Comment pouvons-nous vous aider ?",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Décrivez votre demande en détail...",
    "contact.send": "Envoyer le message",
    "contact.sending": "Envoi en cours...",
    "contact.success": "Message envoyé !",
    "contact.successDesc": "Merci de nous avoir contacté. Notre équipe vous répondra dans les plus brefs délais.",
    "contact.sendAnother": "Envoyer un autre message",
    "contact.location": "Notre emplacement",
    "contact.faqTitle": "Questions fréquentes",
    "contact.faqDesc": "Vous trouverez peut-être la réponse à votre question dans notre FAQ.",
    "contact.faqLink": "Consulter la FAQ",
  },
  nl: {
    // Navigation
    "nav.buy": "Kopen",
    "nav.sell": "Verkopen",
    "nav.favorites": "Favorieten",
    "nav.compare": "Vergelijken",
    "nav.messages": "Berichten",
    "nav.dashboard": "Dashboard",
    "nav.settings": "Instellingen",
    "nav.faq": "FAQ",
    "nav.login": "Inloggen",
    "nav.logout": "Uitloggen",
    "nav.language": "Taal",
    "theme.light": "Lichte modus",
    "theme.dark": "Donkere modus",
    "logout.success": "Uitloggen",
    "logout.description": "U bent succesvol uitgelogd",
    
    // Hero
    "hero.badge": "Belgische automarkt",
    "hero.title1": "Vind uw volgende",
    "hero.title2": "auto in België",
    "hero.subtitle": "Duizenden geverifieerde voertuigen, met Car-Pass en gegarandeerde LEZ-compatibiliteit",
    "hero.search": "Zoeken",
    "hero.vehicles": "Voertuigen",
    "hero.verified": "Car-Pass geverifieerd",
    "hero.brands": "Merken",
    
    // Brands
    "brands.title": "Populaire merken in België",
    
    // Filters
    "filters.title": "Filters",
    "filters.vehicles": "voertuigen",
    "filters.brand": "Merk",
    "filters.allBrands": "Alle merken",
    "filters.model": "Model",
    "filters.budget": "Budget",
    "filters.year": "Jaar",
    "filters.mileage": "Kilometerstand",
    "filters.fuel": "Brandstof",
    "filters.transmission": "Transmissie",
    "filters.euroNorm": "Euronorm (LEZ)",
    "filters.lezOnly": "Alleen LEZ-compatibel",
    "filters.reset": "Filters resetten",
    "filters.allModels": "Alle modellen",
    "filters.selectBrandFirst": "Selecteer eerst een merk",
    "filters.gasoline": "Benzine",
    "filters.diesel": "Diesel",
    "filters.hybrid": "Hybride",
    "filters.electric": "Elektrisch",
    "filters.manual": "Manueel",
    "filters.automatic": "Automatisch",
    
    // Car Card & Detail
    "car.addCompare": "Toevoegen aan vergelijker",
    "car.removeCompare": "Verwijderen uit vergelijker",
    "car.addedCompare": "Toegevoegd aan vergelijker",
    "car.removedCompare": "Verwijderd uit vergelijker",
    "car.maxCompare": "Maximum 3 voertuigen in vergelijker",
    "car.notFound": "Voertuig niet gevonden",
    "car.notFoundDesc": "Dit voertuig bestaat niet of is uit de verkoop gehaald.",
    "car.backToListings": "Terug naar advertenties",
    "car.backToResults": "Terug naar resultaten",
    "car.specifications": "Specificaties",
    "car.description": "Beschrijving",
    "car.sendMessage": "Stuur een bericht",
    "car.callSeller": "Bel de verkoper",
    "car.sendEmail": "Stuur een email",
    "car.linkCopied": "Link gekopieerd!",
    "car.linkCopiedDesc": "De link is naar het klembord gekopieerd",
    "car.relatedCars": "Vergelijkbare voertuigen",
    "car.location": "Locatie",
    "car.disclaimer": "AutoRa is geen betalingsintermediair. Betaal nooit voordat u het voertuig heeft gezien.",
    
    // Auth
    "auth.login": "Inloggen",
    "auth.signup": "Account aanmaken",
    "auth.loginSubtitle": "Log in om toegang te krijgen tot uw ruimte",
    "auth.signupSubtitle": "Registreer om te beginnen",
    "auth.continueGoogle": "Doorgaan met Google",
    "auth.or": "of",
    "auth.fullName": "Volledige naam",
    "auth.email": "E-mailadres",
    "auth.password": "Wachtwoord",
    "auth.submit": "Inloggen",
    "auth.submitSignup": "Registreren",
    "auth.loading": "Laden...",
    "auth.noAccount": "Nog geen account?",
    "auth.hasAccount": "Al een account?",
    "auth.backHome": "Terug naar home",
    "auth.findIdealCar": "Vind uw ideale auto",
    "auth.heroDesc": "Duizenden geverifieerde voertuigen met Car-Pass en gegarandeerde LEZ-compatibiliteit op de Belgische markt.",
    "auth.errorLogin": "Inlogfout",
    "auth.errorCredentials": "E-mail of wachtwoord onjuist",
    "auth.welcome": "Welkom!",
    "auth.loginSuccess": "Succesvol ingelogd",
    "auth.accountExists": "Account bestaat",
    "auth.accountExistsDesc": "Er bestaat al een account met dit e-mailadres",
    "auth.accountCreated": "Account aangemaakt!",
    "auth.accountCreatedDesc": "Uw account is succesvol aangemaakt",
    "auth.error": "Fout",
    "auth.unexpectedError": "Er is een onverwachte fout opgetreden",
    "auth.invalidEmail": "Ongeldig e-mailadres",
    "auth.passwordMin": "Het wachtwoord moet minimaal 6 tekens bevatten",
    "auth.passwordMinStrong": "Het wachtwoord moet minimaal 8 tekens bevatten",
    "auth.passwordUppercase": "Het wachtwoord moet minimaal één hoofdletter bevatten",
    "auth.passwordLowercase": "Het wachtwoord moet minimaal één kleine letter bevatten",
    "auth.passwordNumber": "Het wachtwoord moet minimaal één cijfer bevatten",
    "auth.passwordSpecial": "Het wachtwoord moet minimaal één speciaal teken bevatten",
    "auth.nameMin": "De naam moet minimaal 2 tekens bevatten",
    "auth.forgotPassword": "Wachtwoord vergeten",
    "auth.forgotPasswordDesc": "Voer uw e-mailadres in en wij sturen u een link om uw wachtwoord te resetten.",
    "auth.forgotPasswordLink": "Wachtwoord vergeten?",
    "auth.sendResetLink": "Link versturen",
    "auth.resetEmailSent": "E-mail verzonden!",
    "auth.resetEmailSentDesc": "Controleer uw inbox om uw wachtwoord te resetten.",
    "auth.backToLogin": "Terug naar inloggen",
    "auth.newPassword": "Nieuw wachtwoord",
    "auth.newPasswordDesc": "Kies een nieuw veilig wachtwoord voor uw account.",
    "auth.newPasswordPlaceholder": "Nieuw wachtwoord",
    "auth.confirmPasswordPlaceholder": "Bevestig wachtwoord",
    "auth.passwordsNotMatch": "Wachtwoorden komen niet overeen",
    "auth.resetPasswordSubmit": "Wachtwoord resetten",
    "auth.passwordResetSuccess": "Wachtwoord gereset!",
    "auth.passwordResetSuccessDesc": "Uw wachtwoord is succesvol gewijzigd.",
    "auth.goToHome": "Naar startpagina",
    "auth.resetLinkExpired": "De resetlink is verlopen of ongeldig.",
    "auth.verificationEmailSent": "Controleer uw e-mail",
    "auth.verificationEmailSentDesc": "We hebben een verificatie-e-mail naar uw adres gestuurd. Klik op de link om uw account te activeren.",
    "auth.checkSpam": "Controleer ook uw spam-map als u de e-mail niet kunt vinden.",
    "auth.emailNotVerified": "E-mail niet geverifieerd",
    "auth.emailNotVerifiedDesc": "Verifieer uw e-mail voordat u inlogt.",
    "auth.resendEmail": "Verificatie-e-mail opnieuw verzenden",
    "auth.resendSuccess": "E-mail verzonden!",
    "auth.resendSuccessDesc": "Er is een nieuwe verificatie-e-mail verzonden.",
    
    // Sell Car
    "sell.title": "Verkoop uw auto",
    "sell.editTitle": "Wijzig uw advertentie",
    "sell.subtitle": "Plaats uw advertentie in enkele minuten en bereik duizenden kopers in België",
    "sell.editSubtitle": "Werk de informatie van uw voertuig bij",
    "sell.loginToSell": "Log in om te verkopen",
    "sell.loginDesc": "Maak een gratis account aan om uw advertentie te plaatsen en uw voertuigen te beheren.",
    "sell.secureListings": "Beveiligde advertenties",
    "sell.quickPublish": "Snelle publicatie",
    "sell.carpassVerification": "Car-Pass verificatie",
    "sell.loginSignup": "Inloggen / Registreren",
    
    // FAQ
    "faq.helpCenter": "Helpcentrum",
    "faq.title": "Veelgestelde vragen",
    "faq.subtitle": "Vind snel antwoorden op uw vragen over AutoRa, de Car-Pass, LEZ-zones en meer.",
    "faq.searchPlaceholder": "Zoek een vraag...",
    "faq.all": "Alle",
    "faq.buying": "Een auto kopen",
    "faq.selling": "Verkopen op AutoRa",
    "faq.lezCarpass": "LEZ & Car-Pass",
    "faq.securityPrivacy": "Beveiliging & Privacy",
    "faq.account": "Account",
    "faq.purchase": "Aankoop",
    "faq.sale": "Verkoop",
    "faq.security": "Beveiliging",
    "faq.payment": "Betaling",
    "faq.noResults": "Geen vragen komen overeen met uw zoekopdracht.",
    "faq.resultsFor": "resultaten gevonden",
    "faq.resultFor": "resultaat gevonden",
    "faq.noResult": "Geen resultaten",
    "faq.for": "voor",
    "faq.in": "in",
    "faq.notFound": "Uw antwoord niet gevonden?",
    "faq.notFoundDesc": "Ons team staat voor u klaar. Neem contact met ons op via contact@autora.be",
    "faq.contactUs": "Neem contact op",
    "faq.linkCopied": "Link gekopieerd!",
    
    // Footer
    "footer.description": "De betrouwbare Belgische automarktplaats. Al onze voertuigen zijn geverifieerd met Car-Pass.",
    "footer.navigation": "Navigatie",
    "footer.buyCar": "Een auto kopen",
    "footer.sellCar": "Mijn auto verkopen",
    "footer.estimate": "Mijn voertuig schatten",
    "footer.lezGuide": "LEZ-gids België",
    "footer.info": "Informatie",
    "footer.about": "Over ons",
    "footer.carpass": "Car-Pass België",
    "footer.terms": "Algemene voorwaarden",
    "footer.privacy": "Privacybeleid",
    "footer.legal": "Wettelijke vermeldingen",
    "footer.contact": "Contact",
    "footer.contactForm": "Contactformulier",
    "footer.rights": "Alle rechten voorbehouden.",
    "footer.madeWith": "Gemaakt met ❤️ in België",
    "footer.slogan": "Uw auto met vertrouwen",
    "footer.tagline": "Vind uw volgende auto op het eerste autoplatform gewijd aan de Belgische markt.",
    "footer.warning": "Opgelet",
    "footer.warningText": "Autora is een advertentieplatform. Wij zijn niet verantwoordelijk voor de transactie of de staat van het voertuig. Betaal nooit een voorschot zonder de verkoper persoonlijk te hebben ontmoet en het voertuig te hebben gecontroleerd.",
    "footer.gdprTitle": "Privacy (GDPR)",
    "footer.gdprText": "Uw persoonlijke gegevens worden verwerkt in overeenstemming met de Europese GDPR-wetgeving. U heeft recht op toegang, rectificatie en verwijdering van uw gegevens. Neem contact met ons op via contact@autora.be voor elke aanvraag.",
    
    // Messages
    "messages.title": "Berichten",
    "messages.noMessages": "Geen berichten",
    "messages.noMessagesDesc": "U heeft nog geen gesprekken. Neem contact op met een verkoper om te beginnen.",
    "messages.viewVehicles": "Bekijk voertuigen",
    "messages.conversations": "Gesprekken",
    "messages.noMessage": "Geen bericht",
    "messages.selectConversation": "Selecteer een gesprek",
    "messages.yesterday": "Gisteren",
    
    // Settings
    "settings.title": "Instellingen",
    "settings.back": "Terug",
    "settings.notifications": "Meldingen",
    "settings.notificationsDesc": "Beheer uw meldingsvoorkeuren",
    "settings.emailNotifications": "E-mailmeldingen",
    "settings.emailNotificationsDesc": "Ontvang een e-mail wanneer een koper u een bericht stuurt",
    "settings.emailEnabled": "E-mailmeldingen ingeschakeld",
    "settings.emailDisabled": "E-mailmeldingen uitgeschakeld",
    "settings.errorUpdate": "Fout bij het bijwerken van voorkeuren",
    "settings.account": "Account",
    "settings.accountDesc": "Uw accountgegevens",
    "settings.email": "E-mail",
    
    // Dashboard
    "dashboard.sellerArea": "Verkopersruimte",
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Volg de prestaties van uw advertenties",
    "dashboard.exportCSV": "Exporteer CSV",
    "dashboard.listings": "Advertenties",
    "dashboard.totalViews": "Totale weergaven",
    "dashboard.messages": "Berichten",
    "dashboard.favorites": "Favorieten",
    "dashboard.globalPerformance": "Globale prestaties",
    "dashboard.noDataAvailable": "Geen gegevens beschikbaar",
    "dashboard.detailByListing": "Detail per advertentie",
    "dashboard.noListingsYet": "U heeft nog geen advertenties",
    "dashboard.createListing": "Maak een advertentie",
    "dashboard.views": "Weergaven",
    "dashboard.published": "Gepubliceerd",
    "dashboard.pending": "In afwachting",
    "dashboard.rejected": "Geweigerd",
    "dashboard.deleteListing": "Deze advertentie verwijderen?",
    "dashboard.deleteConfirm": "Weet u zeker dat u de advertentie wilt verwijderen voor",
    "dashboard.deleteIrreversible": "Deze actie is onomkeerbaar.",
    "dashboard.cancel": "Annuleren",
    "dashboard.delete": "Verwijderen",
    "dashboard.deleting": "Verwijderen...",
    "dashboard.deleteSuccess": "Advertentie succesvol verwijderd",
    "dashboard.deleteError": "Fout bij het verwijderen",
    "dashboard.csvDownloaded": "CSV-export gedownload",
    "dashboard.vehicle": "Voertuig",
    "dashboard.status": "Status",
    "dashboard.price": "Prijs",
    "dashboard.createdAt": "Aanmaakdatum",
    "dashboard.total": "TOTAAL",
    "dashboard.viewStats": "Bekijk statistieken",

    // Stats
    "stats.analytics": "Analytics",
    "stats.title": "Gedetailleerde statistieken",
    "stats.subtitle": "Analyseer de prestaties van uw advertenties in detail",
    "stats.backToDashboard": "Terug naar dashboard",
    "stats.totalViews": "Totaal weergaven",
    "stats.totalFavorites": "Totaal favorieten",
    "stats.vsPrevious": "vs vorige periode",
    "stats.evolution": "Evolutie in de tijd",
    "stats.evolutionDesc": "Weergaven en favorieten over de geselecteerde periode",
    "stats.views": "Weergaven",
    "stats.favorites": "Favorieten",
    "stats.noData": "Geen gegevens beschikbaar",
    "stats.viewsDistribution": "Verdeling van weergaven",
    "stats.viewsDistributionDesc": "Verdeling van weergaven per voertuig",
    "stats.performanceByVehicle": "Prestaties per voertuig",
    "stats.performanceByVehicleDesc": "Vergelijking van weergaven en favorieten",
    "stats.detailByVehicle": "Detail per voertuig",
    "stats.detailByVehicleDesc": "Rangschikking van uw advertenties op populariteit",
    "stats.noListings": "Geen advertenties beschikbaar",

    // Reviews
    "reviews.title": "Beoordelingen",
    "reviews.review": "beoordeling",
    "reviews.reviews": "beoordelingen",
    "reviews.leaveReview": "Laat uw beoordeling achter",
    "reviews.yourRating": "Uw beoordeling",
    "reviews.commentPlaceholder": "Deel uw ervaring (optioneel)...",
    "reviews.submit": "Beoordeling plaatsen",
    "reviews.submitting": "Plaatsen...",
    "reviews.submitted": "Beoordeling geplaatst",
    "reviews.submittedDesc": "Bedankt voor uw beoordeling!",
    "reviews.deleted": "Beoordeling verwijderd",
    "reviews.noReviews": "Nog geen beoordelingen. Wees de eerste om een beoordeling te geven!",
    "reviews.loginRequired": "Inloggen vereist",
    "reviews.loginRequiredDesc": "Log in om een beoordeling achter te laten",
    "reviews.loginToReview": "Log in om een beoordeling achter te laten voor dit voertuig",
    "reviews.ratingRequired": "Selecteer een beoordeling",
    "reviews.cannotReviewOwn": "U kunt uw eigen advertentie niet beoordelen",
    "reviews.error": "Fout bij het plaatsen",
    
    // Cookie Consent
    "cookie.title": "Wij gebruiken cookies 🍪",
    "cookie.description": "AutoRa gebruikt cookies om uw ervaring te verbeteren, verkeer te analyseren en inhoud te personaliseren. U kunt alle cookies accepteren, weigeren of uw voorkeuren aanpassen.",
    "cookie.acceptAll": "Alles accepteren",
    "cookie.rejectAll": "Alles weigeren",
    "cookie.customize": "Aanpassen",
    "cookie.settings": "Cookie-voorkeuren",
    "cookie.settingsDesc": "Beheer uw cookie-voorkeuren",
    "cookie.essential": "Essentiële cookies",
    "cookie.essentialDesc": "Noodzakelijk voor de werking van de site. Ze kunnen niet worden uitgeschakeld.",
    "cookie.analytics": "Analytische cookies",
    "cookie.analyticsDesc": "Helpen ons te begrijpen hoe u de site gebruikt om deze te verbeteren.",
    "cookie.personalization": "Personalisatiecookies",
    "cookie.personalizationDesc": "Stellen ons in staat om uw voorkeuren te onthouden en relevante aanbevelingen weer te geven.",
    "cookie.alwaysActive": "Altijd actief",
    "cookie.savePreferences": "Mijn voorkeuren opslaan",
    "cookie.moreInfo": "Voor meer informatie, raadpleeg ons",
    "cookie.privacyPolicy": "privacybeleid",
    
    // Contact
    "contact.title": "Neem contact op",
    "contact.subtitle": "Een vraag? Laten we praten",
    "contact.description": "Ons team staat klaar om al uw vragen over de aankoop of verkoop van uw voertuig te beantwoorden.",
    "contact.info": "Contactgegevens",
    "contact.infoDesc": "Verschillende manieren om ons te bereiken",
    "contact.email": "E-mail",
    "contact.phone": "Telefoon",
    "contact.address": "Adres",
    "contact.hours": "Openingstijden",
    "contact.hoursValue": "Ma-Vr: 9u-18u | Za: 10u-16u",
    "contact.fastResponse": "Snelle reactie",
    "contact.fastResponseDesc": "We reageren meestal binnen 24 werkuren.",
    "contact.formTitle": "Stuur ons een bericht",
    "contact.formDesc": "Vul het onderstaande formulier in en we reageren snel",
    "contact.fullName": "Volledige naam",
    "contact.subject": "Onderwerp",
    "contact.subjectPlaceholder": "Hoe kunnen we u helpen?",
    "contact.message": "Bericht",
    "contact.messagePlaceholder": "Beschrijf uw vraag in detail...",
    "contact.send": "Bericht verzenden",
    "contact.sending": "Verzenden...",
    "contact.success": "Bericht verzonden!",
    "contact.successDesc": "Bedankt voor uw bericht. Ons team zal zo snel mogelijk reageren.",
    "contact.sendAnother": "Nog een bericht sturen",
    "contact.location": "Onze locatie",
    "contact.faqTitle": "Veelgestelde vragen",
    "contact.faqDesc": "Misschien vindt u het antwoord op uw vraag in onze FAQ.",
    "contact.faqLink": "Bekijk de FAQ",
  },
  de: {
    // Navigation
    "nav.buy": "Kaufen",
    "nav.sell": "Verkaufen",
    "nav.favorites": "Favoriten",
    "nav.compare": "Vergleichen",
    "nav.messages": "Nachrichten",
    "nav.dashboard": "Dashboard",
    "nav.settings": "Einstellungen",
    "nav.faq": "FAQ",
    "nav.login": "Anmelden",
    "nav.logout": "Abmelden",
    "nav.language": "Sprache",
    "theme.light": "Heller Modus",
    "theme.dark": "Dunkler Modus",
    "logout.success": "Abgemeldet",
    "logout.description": "Sie wurden erfolgreich abgemeldet",
    
    // Hero
    "hero.badge": "Belgischer Automarkt",
    "hero.title1": "Finden Sie Ihr nächstes",
    "hero.title2": "Auto in Belgien",
    "hero.subtitle": "Tausende verifizierte Fahrzeuge mit Car-Pass und garantierter LEZ-Kompatibilität",
    "hero.search": "Suchen",
    "hero.vehicles": "Fahrzeuge",
    "hero.verified": "Car-Pass verifiziert",
    "hero.brands": "Marken",
    
    // Brands
    "brands.title": "Beliebte Marken in Belgien",
    
    // Filters
    "filters.title": "Filter",
    "filters.vehicles": "Fahrzeuge",
    "filters.brand": "Marke",
    "filters.allBrands": "Alle Marken",
    "filters.model": "Modell",
    "filters.budget": "Budget",
    "filters.year": "Jahr",
    "filters.mileage": "Kilometerstand",
    "filters.fuel": "Kraftstoff",
    "filters.transmission": "Getriebe",
    "filters.euroNorm": "Euro-Norm (LEZ)",
    "filters.lezOnly": "Nur LEZ-kompatibel",
    "filters.reset": "Filter zurücksetzen",
    "filters.allModels": "Alle Modelle",
    "filters.selectBrandFirst": "Wählen Sie zuerst eine Marke",
    "filters.gasoline": "Benzin",
    "filters.diesel": "Diesel",
    "filters.hybrid": "Hybrid",
    "filters.electric": "Elektrisch",
    "filters.manual": "Schaltung",
    "filters.automatic": "Automatik",
    
    // Car Card & Detail
    "car.addCompare": "Zum Vergleich hinzufügen",
    "car.removeCompare": "Aus Vergleich entfernen",
    "car.addedCompare": "Zum Vergleich hinzugefügt",
    "car.removedCompare": "Aus Vergleich entfernt",
    "car.maxCompare": "Maximal 3 Fahrzeuge im Vergleich",
    "car.notFound": "Fahrzeug nicht gefunden",
    "car.notFoundDesc": "Dieses Fahrzeug existiert nicht oder wurde aus dem Verkauf genommen.",
    "car.backToListings": "Zurück zu den Anzeigen",
    "car.backToResults": "Zurück zu den Ergebnissen",
    "car.specifications": "Spezifikationen",
    "car.description": "Beschreibung",
    "car.sendMessage": "Nachricht senden",
    "car.callSeller": "Verkäufer anrufen",
    "car.sendEmail": "E-Mail senden",
    "car.linkCopied": "Link kopiert!",
    "car.linkCopiedDesc": "Der Link wurde in die Zwischenablage kopiert",
    "car.relatedCars": "Ähnliche Fahrzeuge",
    "car.location": "Standort",
    "car.disclaimer": "AutoRa ist kein Zahlungsvermittler. Zahlen Sie nie, bevor Sie das Fahrzeug gesehen haben.",
    
    // Auth
    "auth.login": "Anmelden",
    "auth.signup": "Konto erstellen",
    "auth.loginSubtitle": "Melden Sie sich an, um auf Ihren Bereich zuzugreifen",
    "auth.signupSubtitle": "Registrieren Sie sich, um zu beginnen",
    "auth.continueGoogle": "Mit Google fortfahren",
    "auth.or": "oder",
    "auth.fullName": "Vollständiger Name",
    "auth.email": "E-Mail-Adresse",
    "auth.password": "Passwort",
    "auth.submit": "Anmelden",
    "auth.submitSignup": "Registrieren",
    "auth.loading": "Laden...",
    "auth.noAccount": "Noch kein Konto?",
    "auth.hasAccount": "Bereits ein Konto?",
    "auth.backHome": "Zurück zur Startseite",
    "auth.findIdealCar": "Finden Sie Ihr ideales Auto",
    "auth.heroDesc": "Tausende verifizierte Fahrzeuge mit Car-Pass und garantierter LEZ-Kompatibilität auf dem belgischen Markt.",
    "auth.errorLogin": "Anmeldefehler",
    "auth.errorCredentials": "E-Mail oder Passwort falsch",
    "auth.welcome": "Willkommen!",
    "auth.loginSuccess": "Erfolgreich angemeldet",
    "auth.accountExists": "Konto existiert",
    "auth.accountExistsDesc": "Ein Konto mit dieser E-Mail-Adresse existiert bereits",
    "auth.accountCreated": "Konto erstellt!",
    "auth.accountCreatedDesc": "Ihr Konto wurde erfolgreich erstellt",
    "auth.error": "Fehler",
    "auth.unexpectedError": "Ein unerwarteter Fehler ist aufgetreten",
    "auth.invalidEmail": "Ungültige E-Mail-Adresse",
    "auth.passwordMin": "Das Passwort muss mindestens 6 Zeichen enthalten",
    "auth.passwordMinStrong": "Das Passwort muss mindestens 8 Zeichen enthalten",
    "auth.passwordUppercase": "Das Passwort muss mindestens einen Großbuchstaben enthalten",
    "auth.passwordLowercase": "Das Passwort muss mindestens einen Kleinbuchstaben enthalten",
    "auth.passwordNumber": "Das Passwort muss mindestens eine Zahl enthalten",
    "auth.passwordSpecial": "Das Passwort muss mindestens ein Sonderzeichen enthalten",
    "auth.nameMin": "Der Name muss mindestens 2 Zeichen enthalten",
    "auth.forgotPassword": "Passwort vergessen",
    "auth.forgotPasswordDesc": "Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen einen Link zum Zurücksetzen Ihres Passworts.",
    "auth.forgotPasswordLink": "Passwort vergessen?",
    "auth.sendResetLink": "Link senden",
    "auth.resetEmailSent": "E-Mail gesendet!",
    "auth.resetEmailSentDesc": "Überprüfen Sie Ihren Posteingang, um Ihr Passwort zurückzusetzen.",
    "auth.backToLogin": "Zurück zur Anmeldung",
    "auth.newPassword": "Neues Passwort",
    "auth.newPasswordDesc": "Wählen Sie ein neues sicheres Passwort für Ihr Konto.",
    "auth.newPasswordPlaceholder": "Neues Passwort",
    "auth.confirmPasswordPlaceholder": "Passwort bestätigen",
    "auth.passwordsNotMatch": "Passwörter stimmen nicht überein",
    "auth.resetPasswordSubmit": "Passwort zurücksetzen",
    "auth.passwordResetSuccess": "Passwort zurückgesetzt!",
    "auth.passwordResetSuccessDesc": "Ihr Passwort wurde erfolgreich geändert.",
    "auth.goToHome": "Zur Startseite",
    "auth.resetLinkExpired": "Der Reset-Link ist abgelaufen oder ungültig.",
    "auth.verificationEmailSent": "Überprüfen Sie Ihre E-Mail",
    "auth.verificationEmailSentDesc": "Wir haben eine Bestätigungs-E-Mail an Ihre Adresse gesendet. Klicken Sie auf den Link, um Ihr Konto zu aktivieren.",
    "auth.checkSpam": "Überprüfen Sie auch Ihren Spam-Ordner, wenn Sie die E-Mail nicht finden können.",
    "auth.emailNotVerified": "E-Mail nicht verifiziert",
    "auth.emailNotVerifiedDesc": "Bitte verifizieren Sie Ihre E-Mail, bevor Sie sich anmelden.",
    "auth.resendEmail": "Bestätigungs-E-Mail erneut senden",
    "auth.resendSuccess": "E-Mail gesendet!",
    "auth.resendSuccessDesc": "Eine neue Bestätigungs-E-Mail wurde gesendet.",
    
    // Sell Car
    "sell.title": "Verkaufen Sie Ihr Auto",
    "sell.editTitle": "Bearbeiten Sie Ihre Anzeige",
    "sell.subtitle": "Veröffentlichen Sie Ihre Anzeige in wenigen Minuten und erreichen Sie Tausende von Käufern in Belgien",
    "sell.editSubtitle": "Aktualisieren Sie die Informationen Ihres Fahrzeugs",
    "sell.loginToSell": "Melden Sie sich an, um zu verkaufen",
    "sell.loginDesc": "Erstellen Sie ein kostenloses Konto, um Ihre Anzeige zu veröffentlichen und Ihre Fahrzeuge zu verwalten.",
    "sell.secureListings": "Sichere Anzeigen",
    "sell.quickPublish": "Schnelle Veröffentlichung",
    "sell.carpassVerification": "Car-Pass Verifizierung",
    "sell.loginSignup": "Anmelden / Registrieren",
    
    // FAQ
    "faq.helpCenter": "Hilfezentrum",
    "faq.title": "Häufig gestellte Fragen",
    "faq.subtitle": "Finden Sie schnell Antworten auf Ihre Fragen zu AutoRa, dem Car-Pass, LEZ-Zonen und mehr.",
    "faq.searchPlaceholder": "Frage suchen...",
    "faq.all": "Alle",
    "faq.buying": "Ein Auto kaufen",
    "faq.selling": "Auf AutoRa verkaufen",
    "faq.lezCarpass": "LEZ & Car-Pass",
    "faq.securityPrivacy": "Sicherheit & Datenschutz",
    "faq.account": "Konto",
    "faq.purchase": "Kauf",
    "faq.sale": "Verkauf",
    "faq.security": "Sicherheit",
    "faq.payment": "Zahlung",
    "faq.noResults": "Keine Fragen entsprechen Ihrer Suche.",
    "faq.resultsFor": "Ergebnisse gefunden",
    "faq.resultFor": "Ergebnis gefunden",
    "faq.noResult": "Keine Ergebnisse",
    "faq.for": "für",
    "faq.in": "in",
    "faq.notFound": "Ihre Antwort nicht gefunden?",
    "faq.notFoundDesc": "Unser Team ist für Sie da. Kontaktieren Sie uns per E-Mail unter contact@autora.be",
    "faq.contactUs": "Kontaktieren Sie uns",
    "faq.linkCopied": "Link kopiert!",
    
    // Footer
    "footer.description": "Der vertrauenswürdige belgische Automarktplatz. Alle unsere Fahrzeuge sind mit Car-Pass verifiziert.",
    "footer.navigation": "Navigation",
    "footer.buyCar": "Ein Auto kaufen",
    "footer.sellCar": "Mein Auto verkaufen",
    "footer.estimate": "Mein Fahrzeug schätzen",
    "footer.lezGuide": "LEZ-Leitfaden Belgien",
    "footer.info": "Informationen",
    "footer.about": "Über uns",
    "footer.carpass": "Car-Pass Belgien",
    "footer.terms": "Allgemeine Geschäftsbedingungen",
    "footer.privacy": "Datenschutzrichtlinie",
    "footer.legal": "Impressum",
    "footer.contact": "Kontakt",
    "footer.contactForm": "Kontaktformular",
    "footer.rights": "Alle Rechte vorbehalten.",
    "footer.madeWith": "Mit ❤️ in Belgien gemacht",
    "footer.slogan": "Ihr Auto mit Vertrauen",
    "footer.tagline": "Finden Sie Ihr nächstes Auto auf der ersten Autoanzeigerplattform für den belgischen Markt.",
    "footer.warning": "Achtung",
    "footer.warningText": "Autora ist eine Anzeigenplattform. Wir sind nicht verantwortlich für die Transaktion oder den Zustand des Fahrzeugs. Zahlen Sie niemals eine Anzahlung, ohne den Verkäufer persönlich getroffen und das Fahrzeug überprüft zu haben.",
    "footer.gdprTitle": "Datenschutz (DSGVO)",
    "footer.gdprText": "Ihre persönlichen Daten werden gemäß der europäischen DSGVO-Verordnung verarbeitet. Sie haben das Recht auf Zugang, Berichtigung und Löschung Ihrer Daten. Kontaktieren Sie uns unter contact@autora.be für jede Anfrage.",
    
    // Messages
    "messages.title": "Nachrichten",
    "messages.noMessages": "Keine Nachrichten",
    "messages.noMessagesDesc": "Sie haben noch keine Gespräche. Kontaktieren Sie einen Verkäufer, um zu beginnen.",
    "messages.viewVehicles": "Fahrzeuge ansehen",
    "messages.conversations": "Gespräche",
    "messages.noMessage": "Keine Nachricht",
    "messages.selectConversation": "Wählen Sie ein Gespräch",
    "messages.yesterday": "Gestern",
    
    // Settings
    "settings.title": "Einstellungen",
    "settings.back": "Zurück",
    "settings.notifications": "Benachrichtigungen",
    "settings.notificationsDesc": "Verwalten Sie Ihre Benachrichtigungseinstellungen",
    "settings.emailNotifications": "E-Mail-Benachrichtigungen",
    "settings.emailNotificationsDesc": "Erhalten Sie eine E-Mail, wenn ein Käufer Ihnen eine Nachricht sendet",
    "settings.emailEnabled": "E-Mail-Benachrichtigungen aktiviert",
    "settings.emailDisabled": "E-Mail-Benachrichtigungen deaktiviert",
    "settings.errorUpdate": "Fehler beim Aktualisieren der Einstellungen",
    "settings.account": "Konto",
    "settings.accountDesc": "Ihre Kontoinformationen",
    "settings.email": "E-Mail",
    
    // Dashboard
    "dashboard.sellerArea": "Verkäuferbereich",
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Verfolgen Sie die Leistung Ihrer Anzeigen",
    "dashboard.exportCSV": "CSV exportieren",
    "dashboard.listings": "Anzeigen",
    "dashboard.totalViews": "Gesamtaufrufe",
    "dashboard.messages": "Nachrichten",
    "dashboard.favorites": "Favoriten",
    "dashboard.globalPerformance": "Gesamtleistung",
    "dashboard.noDataAvailable": "Keine Daten verfügbar",
    "dashboard.detailByListing": "Detail pro Anzeige",
    "dashboard.noListingsYet": "Sie haben noch keine Anzeigen",
    "dashboard.createListing": "Anzeige erstellen",
    "dashboard.views": "Aufrufe",
    "dashboard.published": "Veröffentlicht",
    "dashboard.pending": "Ausstehend",
    "dashboard.rejected": "Abgelehnt",
    "dashboard.deleteListing": "Diese Anzeige löschen?",
    "dashboard.deleteConfirm": "Sind Sie sicher, dass Sie die Anzeige löschen möchten für",
    "dashboard.deleteIrreversible": "Diese Aktion ist unwiderruflich.",
    "dashboard.cancel": "Abbrechen",
    "dashboard.delete": "Löschen",
    "dashboard.deleting": "Löschen...",
    "dashboard.deleteSuccess": "Anzeige erfolgreich gelöscht",
    "dashboard.deleteError": "Fehler beim Löschen",
    "dashboard.csvDownloaded": "CSV-Export heruntergeladen",
    "dashboard.vehicle": "Fahrzeug",
    "dashboard.status": "Status",
    "dashboard.price": "Preis",
    "dashboard.createdAt": "Erstellt am",
    "dashboard.total": "GESAMT",
    "dashboard.viewStats": "Statistiken anzeigen",

    // Stats
    "stats.analytics": "Analysen",
    "stats.title": "Detaillierte Statistiken",
    "stats.subtitle": "Analysieren Sie die Leistung Ihrer Anzeigen im Detail",
    "stats.backToDashboard": "Zurück zum Dashboard",
    "stats.totalViews": "Gesamtaufrufe",
    "stats.totalFavorites": "Gesamtfavoriten",
    "stats.vsPrevious": "vs. vorheriger Zeitraum",
    "stats.evolution": "Entwicklung über die Zeit",
    "stats.evolutionDesc": "Aufrufe und Favoriten im ausgewählten Zeitraum",
    "stats.views": "Aufrufe",
    "stats.favorites": "Favoriten",
    "stats.noData": "Keine Daten verfügbar",
    "stats.viewsDistribution": "Aufrufverteilung",
    "stats.viewsDistributionDesc": "Verteilung der Aufrufe pro Fahrzeug",
    "stats.performanceByVehicle": "Leistung pro Fahrzeug",
    "stats.performanceByVehicleDesc": "Vergleich von Aufrufen und Favoriten",
    "stats.detailByVehicle": "Detail pro Fahrzeug",
    "stats.detailByVehicleDesc": "Ranking Ihrer Anzeigen nach Beliebtheit",
    "stats.noListings": "Keine Anzeigen verfügbar",

    // Reviews
    "reviews.title": "Bewertungen",
    "reviews.review": "Bewertung",
    "reviews.reviews": "Bewertungen",
    "reviews.leaveReview": "Hinterlassen Sie Ihre Bewertung",
    "reviews.yourRating": "Ihre Bewertung",
    "reviews.commentPlaceholder": "Teilen Sie Ihre Erfahrung (optional)...",
    "reviews.submit": "Bewertung absenden",
    "reviews.submitting": "Absenden...",
    "reviews.submitted": "Bewertung abgesendet",
    "reviews.submittedDesc": "Vielen Dank für Ihre Bewertung!",
    "reviews.deleted": "Bewertung gelöscht",
    "reviews.noReviews": "Noch keine Bewertungen. Seien Sie der Erste, der eine Bewertung abgibt!",
    "reviews.loginRequired": "Anmeldung erforderlich",
    "reviews.loginRequiredDesc": "Bitte melden Sie sich an, um eine Bewertung abzugeben",
    "reviews.loginToReview": "Melden Sie sich an, um dieses Fahrzeug zu bewerten",
    "reviews.ratingRequired": "Bitte wählen Sie eine Bewertung",
    "reviews.cannotReviewOwn": "Sie können Ihre eigene Anzeige nicht bewerten",
    "reviews.error": "Fehler beim Absenden",
    
    // Cookie Consent
    "cookie.title": "Wir verwenden Cookies 🍪",
    "cookie.description": "AutoRa verwendet Cookies, um Ihre Erfahrung zu verbessern, den Verkehr zu analysieren und Inhalte zu personalisieren. Sie können alle Cookies akzeptieren, ablehnen oder Ihre Präferenzen anpassen.",
    "cookie.acceptAll": "Alle akzeptieren",
    "cookie.rejectAll": "Alle ablehnen",
    "cookie.customize": "Anpassen",
    "cookie.settings": "Cookie-Einstellungen",
    "cookie.settingsDesc": "Verwalten Sie Ihre Cookie-Einstellungen",
    "cookie.essential": "Essentielle Cookies",
    "cookie.essentialDesc": "Notwendig für den Betrieb der Website. Sie können nicht deaktiviert werden.",
    "cookie.analytics": "Analyse-Cookies",
    "cookie.analyticsDesc": "Helfen uns zu verstehen, wie Sie die Website nutzen, um sie zu verbessern.",
    "cookie.personalization": "Personalisierungs-Cookies",
    "cookie.personalizationDesc": "Ermöglichen es uns, Ihre Präferenzen zu speichern und relevante Empfehlungen anzuzeigen.",
    "cookie.alwaysActive": "Immer aktiv",
    "cookie.savePreferences": "Meine Einstellungen speichern",
    "cookie.moreInfo": "Für weitere Informationen lesen Sie unsere",
    "cookie.privacyPolicy": "Datenschutzrichtlinie",
    
    // Contact
    "contact.title": "Kontaktieren Sie uns",
    "contact.subtitle": "Eine Frage? Lassen Sie uns reden",
    "contact.description": "Unser Team steht Ihnen zur Verfügung, um alle Ihre Fragen zum Kauf oder Verkauf Ihres Fahrzeugs zu beantworten.",
    "contact.info": "Kontaktinformationen",
    "contact.infoDesc": "Verschiedene Möglichkeiten, uns zu erreichen",
    "contact.email": "E-Mail",
    "contact.phone": "Telefon",
    "contact.address": "Adresse",
    "contact.hours": "Öffnungszeiten",
    "contact.hoursValue": "Mo-Fr: 9-18 Uhr | Sa: 10-16 Uhr",
    "contact.fastResponse": "Schnelle Antwort",
    "contact.fastResponseDesc": "Wir antworten normalerweise innerhalb von 24 Geschäftsstunden.",
    "contact.formTitle": "Senden Sie uns eine Nachricht",
    "contact.formDesc": "Füllen Sie das folgende Formular aus und wir werden schnell antworten",
    "contact.fullName": "Vollständiger Name",
    "contact.subject": "Betreff",
    "contact.subjectPlaceholder": "Wie können wir Ihnen helfen?",
    "contact.message": "Nachricht",
    "contact.messagePlaceholder": "Beschreiben Sie Ihre Anfrage im Detail...",
    "contact.send": "Nachricht senden",
    "contact.sending": "Senden...",
    "contact.success": "Nachricht gesendet!",
    "contact.successDesc": "Vielen Dank für Ihre Kontaktaufnahme. Unser Team wird so schnell wie möglich antworten.",
    "contact.sendAnother": "Weitere Nachricht senden",
    "contact.location": "Unser Standort",
    "contact.faqTitle": "Häufig gestellte Fragen",
    "contact.faqDesc": "Vielleicht finden Sie die Antwort auf Ihre Frage in unseren FAQ.",
    "contact.faqLink": "FAQ ansehen",
  },
};

const languageLabels: Record<Language, string> = {
  fr: "FR",
  nl: "NL",
  de: "DE",
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Detect browser language
const detectBrowserLanguage = (): Language => {
  const browserLang = navigator.language.split("-")[0];
  if (browserLang === "de") return "de";
  if (browserLang === "nl") return "nl";
  return "fr"; // Default to French
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    if (saved && (saved === "fr" || saved === "nl" || saved === "de")) {
      return saved as Language;
    }
    return detectBrowserLanguage();
  });

  useEffect(() => {
    // Set html lang attribute for SEO
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.fr[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export const getLanguageLabel = (lang: Language) => languageLabels[lang];
