import { createContext, useContext, useState, ReactNode } from "react";

type Language = "fr" | "nl" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    "nav.buy": "Acheter",
    "nav.sell": "Vendre",
    "nav.favorites": "Favoris",
    "nav.compare": "Comparer",
    "nav.messages": "Messages",
    "nav.dashboard": "Dashboard",
    "nav.settings": "Paramètres",
    "nav.faq": "FAQ",
    "nav.login": "Connexion",
    "nav.logout": "Déconnexion",
    "theme.light": "Mode clair",
    "theme.dark": "Mode sombre",
    "logout.success": "Déconnexion",
    "logout.description": "Vous avez été déconnecté avec succès",
    
    // Hero
    "hero.badge": "Marché automobile belge",
    "hero.title1": "Trouvez votre prochaine",
    "hero.title2": "voiture en Belgique",
    "hero.subtitle": "Des milliers de véhicules vérifiés, avec Car-Pass et compatibilité LEZ garantie",
    "hero.search": "Rechercher",
    "hero.vehicles": "Véhicules",
    "hero.verified": "Car-Pass vérifié",
    "hero.brands": "Marques",
    
    // Filters
    "filters.title": "Filtres",
    "filters.vehicles": "véhicules",
    "filters.brand": "Marque",
    "filters.allBrands": "Toutes les marques",
    "filters.model": "Modèle",
    "filters.budget": "Budget",
    "filters.year": "Année",
    "filters.mileage": "Kilométrage",
    "filters.fuel": "Carburant",
    "filters.transmission": "Boîte de vitesse",
    "filters.euroNorm": "Norme Euro (LEZ)",
    "filters.lezOnly": "Compatible LEZ uniquement",
    "filters.reset": "Réinitialiser les filtres",
    "filters.gasoline": "Essence",
    "filters.diesel": "Diesel",
    "filters.hybrid": "Hybride",
    "filters.electric": "Électrique",
    "filters.manual": "Manuelle",
    "filters.automatic": "Automatique",
    
    // Car Card & Detail
    "car.addCompare": "Ajouter au comparateur",
    "car.removeCompare": "Retirer du comparateur",
    "car.addedCompare": "Ajouté au comparateur",
    "car.removedCompare": "Retiré du comparateur",
    "car.maxCompare": "Maximum 3 véhicules dans le comparateur",
    "car.notFound": "Véhicule non trouvé",
    "car.notFoundDesc": "Ce véhicule n'existe pas ou a été retiré de la vente.",
    "car.backToListings": "Retour aux annonces",
    "car.backToResults": "Retour aux résultats",
    "car.specifications": "Caractéristiques",
    "car.description": "Description",
    "car.sendMessage": "Envoyer un message",
    "car.callSeller": "Appeler le vendeur",
    "car.sendEmail": "Envoyer un email",
    "car.linkCopied": "Lien copié !",
    "car.linkCopiedDesc": "Le lien a été copié dans le presse-papier",
    "car.relatedCars": "Véhicules similaires",
    "car.location": "Localisation",
    "car.disclaimer": "AutoRa n'est pas intermédiaire de paiement. Ne payez jamais avant d'avoir vu le véhicule.",
    
    // Auth
    "auth.login": "Connexion",
    "auth.signup": "Créer un compte",
    "auth.loginSubtitle": "Connectez-vous pour accéder à votre espace",
    "auth.signupSubtitle": "Inscrivez-vous pour commencer",
    "auth.continueGoogle": "Continuer avec Google",
    "auth.or": "ou",
    "auth.fullName": "Nom complet",
    "auth.email": "Adresse email",
    "auth.password": "Mot de passe",
    "auth.submit": "Se connecter",
    "auth.submitSignup": "S'inscrire",
    "auth.loading": "Chargement...",
    "auth.noAccount": "Pas encore de compte ?",
    "auth.hasAccount": "Déjà un compte ?",
    "auth.backHome": "Retour à l'accueil",
    "auth.findIdealCar": "Trouvez votre voiture idéale",
    "auth.heroDesc": "Des milliers de véhicules vérifiés avec Car-Pass et compatibilité LEZ garantie sur le marché belge.",
    "auth.errorLogin": "Erreur de connexion",
    "auth.errorCredentials": "Email ou mot de passe incorrect",
    "auth.welcome": "Bienvenue !",
    "auth.loginSuccess": "Connexion réussie",
    "auth.accountExists": "Compte existant",
    "auth.accountExistsDesc": "Un compte existe déjà avec cette adresse email",
    "auth.accountCreated": "Compte créé !",
    "auth.accountCreatedDesc": "Votre compte a été créé avec succès",
    "auth.error": "Erreur",
    "auth.unexpectedError": "Une erreur inattendue s'est produite",
    "auth.invalidEmail": "Adresse email invalide",
    "auth.passwordMin": "Le mot de passe doit contenir au moins 6 caractères",
    "auth.passwordMinStrong": "Le mot de passe doit contenir au moins 8 caractères",
    "auth.passwordUppercase": "Le mot de passe doit contenir au moins une majuscule",
    "auth.passwordLowercase": "Le mot de passe doit contenir au moins une minuscule",
    "auth.passwordNumber": "Le mot de passe doit contenir au moins un chiffre",
    "auth.passwordSpecial": "Le mot de passe doit contenir au moins un caractère spécial",
    "auth.nameMin": "Le nom doit contenir au moins 2 caractères",
    "auth.forgotPassword": "Mot de passe oublié",
    "auth.forgotPasswordDesc": "Entrez votre adresse email et nous vous enverrons un lien pour réinitialiser votre mot de passe.",
    "auth.forgotPasswordLink": "Mot de passe oublié ?",
    "auth.sendResetLink": "Envoyer le lien",
    "auth.resetEmailSent": "Email envoyé !",
    "auth.resetEmailSentDesc": "Consultez votre boîte de réception pour réinitialiser votre mot de passe.",
    "auth.backToLogin": "Retour à la connexion",
    "auth.newPassword": "Nouveau mot de passe",
    "auth.newPasswordDesc": "Choisissez un nouveau mot de passe sécurisé pour votre compte.",
    "auth.newPasswordPlaceholder": "Nouveau mot de passe",
    "auth.confirmPasswordPlaceholder": "Confirmer le mot de passe",
    "auth.passwordsNotMatch": "Les mots de passe ne correspondent pas",
    "auth.resetPasswordSubmit": "Réinitialiser le mot de passe",
    "auth.passwordResetSuccess": "Mot de passe réinitialisé !",
    "auth.passwordResetSuccessDesc": "Votre mot de passe a été modifié avec succès.",
    "auth.goToHome": "Aller à l'accueil",
    "auth.resetLinkExpired": "Le lien de réinitialisation a expiré ou est invalide.",
    "auth.verificationEmailSent": "Vérifiez votre email",
    "auth.verificationEmailSentDesc": "Nous avons envoyé un email de vérification à votre adresse. Cliquez sur le lien pour activer votre compte.",
    "auth.checkSpam": "Vérifiez également votre dossier spam si vous ne trouvez pas l'email.",
    "auth.emailNotVerified": "Email non vérifié",
    "auth.emailNotVerifiedDesc": "Veuillez vérifier votre email avant de vous connecter.",
    "auth.resendEmail": "Renvoyer l'email de vérification",
    "auth.resendSuccess": "Email envoyé !",
    "auth.resendSuccessDesc": "Un nouvel email de vérification a été envoyé.",
    
    // Sell Car
    "sell.title": "Vendez votre voiture",
    "sell.editTitle": "Modifier votre annonce",
    "sell.subtitle": "Publiez votre annonce en quelques minutes et touchez des milliers d'acheteurs en Belgique",
    "sell.editSubtitle": "Mettez à jour les informations de votre véhicule",
    "sell.loginToSell": "Connectez-vous pour vendre",
    "sell.loginDesc": "Créez un compte gratuit pour publier votre annonce et gérer vos véhicules.",
    "sell.secureListings": "Annonces sécurisées",
    "sell.quickPublish": "Publication rapide",
    "sell.carpassVerification": "Vérification Car-Pass",
    "sell.loginSignup": "Se connecter / S'inscrire",
    
    // FAQ
    "faq.helpCenter": "Centre d'aide",
    "faq.title": "Questions fréquentes",
    "faq.subtitle": "Trouvez rapidement les réponses à vos questions sur AutoRa, le Car-Pass, les zones LEZ et bien plus encore.",
    "faq.searchPlaceholder": "Rechercher une question...",
    "faq.all": "Toutes",
    "faq.account": "Compte",
    "faq.purchase": "Achat",
    "faq.sale": "Vente",
    "faq.security": "Sécurité",
    "faq.payment": "Paiement",
    "faq.noResults": "Aucune question ne correspond à votre recherche.",
    "faq.resultsFor": "résultats trouvés",
    "faq.resultFor": "résultat trouvé",
    "faq.noResult": "Aucun résultat",
    "faq.for": "pour",
    "faq.in": "dans",
    "faq.notFound": "Vous n'avez pas trouvé votre réponse ?",
    "faq.notFoundDesc": "Notre équipe est là pour vous aider. Contactez-nous par email à contact@autora.be",
    "faq.contactUs": "Nous contacter",
    "faq.linkCopied": "Lien copié !",
    
    // Footer
    "footer.description": "La marketplace automobile belge de confiance. Tous nos véhicules sont vérifiés avec Car-Pass.",
    "footer.navigation": "Navigation",
    "footer.buyCar": "Acheter une voiture",
    "footer.sellCar": "Vendre ma voiture",
    "footer.estimate": "Estimer mon véhicule",
    "footer.lezGuide": "Guide LEZ Belgique",
    "footer.info": "Informations",
    "footer.about": "À propos de nous",
    "footer.carpass": "Car-Pass Belgique",
    "footer.terms": "Conditions générales",
    "footer.privacy": "Politique de confidentialité",
    "footer.legal": "Mentions légales",
    "footer.contact": "Contact",
    "footer.rights": "Tous droits réservés.",
    "footer.madeWith": "Fait avec ❤️ en Belgique",
    
    // Messages
    "messages.title": "Messages",
    "messages.noMessages": "Aucun message",
    "messages.noMessagesDesc": "Vous n'avez pas encore de conversations. Contactez un vendeur pour commencer.",
    "messages.viewVehicles": "Voir les véhicules",
    "messages.conversations": "Conversations",
    "messages.noMessage": "Aucun message",
    "messages.selectConversation": "Sélectionnez une conversation",
    "messages.yesterday": "Hier",
    
    // Settings
    "settings.title": "Paramètres",
    "settings.back": "Retour",
    "settings.notifications": "Notifications",
    "settings.notificationsDesc": "Gérez vos préférences de notifications",
    "settings.emailNotifications": "Notifications par email",
    "settings.emailNotificationsDesc": "Recevez un email quand un acheteur vous envoie un message",
    "settings.emailEnabled": "Notifications email activées",
    "settings.emailDisabled": "Notifications email désactivées",
    "settings.errorUpdate": "Erreur lors de la mise à jour des préférences",
    "settings.account": "Compte",
    "settings.accountDesc": "Informations de votre compte",
    "settings.email": "Email",
    
    // Dashboard
    "dashboard.sellerArea": "Espace vendeur",
    "dashboard.title": "Tableau de bord",
    "dashboard.subtitle": "Suivez les performances de vos annonces",
    "dashboard.exportCSV": "Exporter CSV",
    "dashboard.listings": "Annonces",
    "dashboard.totalViews": "Vues totales",
    "dashboard.messages": "Messages",
    "dashboard.favorites": "Favoris",
    "dashboard.globalPerformance": "Performance globale",
    "dashboard.noDataAvailable": "Aucune donnée disponible",
    "dashboard.detailByListing": "Détail par annonce",
    "dashboard.noListingsYet": "Vous n'avez pas encore d'annonces",
    "dashboard.createListing": "Créer une annonce",
    "dashboard.views": "Vues",
    "dashboard.published": "Publiée",
    "dashboard.pending": "En attente",
    "dashboard.rejected": "Refusée",
    "dashboard.deleteListing": "Supprimer cette annonce ?",
    "dashboard.deleteConfirm": "Êtes-vous sûr de vouloir supprimer l'annonce pour",
    "dashboard.deleteIrreversible": "Cette action est irréversible.",
    "dashboard.cancel": "Annuler",
    "dashboard.delete": "Supprimer",
    "dashboard.deleting": "Suppression...",
    "dashboard.deleteSuccess": "Annonce supprimée avec succès",
    "dashboard.deleteError": "Erreur lors de la suppression",
    "dashboard.csvDownloaded": "Export CSV téléchargé",
    "dashboard.vehicle": "Véhicule",
    "dashboard.status": "Statut",
    "dashboard.price": "Prix",
    "dashboard.createdAt": "Date de création",
    "dashboard.total": "TOTAL",
  },
  nl: {
    // Navigation
    "nav.buy": "Kopen",
    "nav.sell": "Verkopen",
    "nav.favorites": "Favorieten",
    "nav.compare": "Vergelijken",
    "nav.messages": "Berichten",
    "nav.dashboard": "Dashboard",
    "nav.settings": "Instellingen",
    "nav.faq": "FAQ",
    "nav.login": "Inloggen",
    "nav.logout": "Uitloggen",
    "theme.light": "Lichte modus",
    "theme.dark": "Donkere modus",
    "logout.success": "Uitloggen",
    "logout.description": "U bent succesvol uitgelogd",
    
    // Hero
    "hero.badge": "Belgische automarkt",
    "hero.title1": "Vind uw volgende",
    "hero.title2": "auto in België",
    "hero.subtitle": "Duizenden geverifieerde voertuigen, met Car-Pass en gegarandeerde LEZ-compatibiliteit",
    "hero.search": "Zoeken",
    "hero.vehicles": "Voertuigen",
    "hero.verified": "Car-Pass geverifieerd",
    "hero.brands": "Merken",
    
    // Filters
    "filters.title": "Filters",
    "filters.vehicles": "voertuigen",
    "filters.brand": "Merk",
    "filters.allBrands": "Alle merken",
    "filters.model": "Model",
    "filters.budget": "Budget",
    "filters.year": "Jaar",
    "filters.mileage": "Kilometerstand",
    "filters.fuel": "Brandstof",
    "filters.transmission": "Transmissie",
    "filters.euroNorm": "Euronorm (LEZ)",
    "filters.lezOnly": "Alleen LEZ-compatibel",
    "filters.reset": "Filters resetten",
    "filters.gasoline": "Benzine",
    "filters.diesel": "Diesel",
    "filters.hybrid": "Hybride",
    "filters.electric": "Elektrisch",
    "filters.manual": "Manueel",
    "filters.automatic": "Automatisch",
    
    // Car Card & Detail
    "car.addCompare": "Toevoegen aan vergelijker",
    "car.removeCompare": "Verwijderen uit vergelijker",
    "car.addedCompare": "Toegevoegd aan vergelijker",
    "car.removedCompare": "Verwijderd uit vergelijker",
    "car.maxCompare": "Maximum 3 voertuigen in vergelijker",
    "car.notFound": "Voertuig niet gevonden",
    "car.notFoundDesc": "Dit voertuig bestaat niet of is uit de verkoop gehaald.",
    "car.backToListings": "Terug naar advertenties",
    "car.backToResults": "Terug naar resultaten",
    "car.specifications": "Specificaties",
    "car.description": "Beschrijving",
    "car.sendMessage": "Stuur een bericht",
    "car.callSeller": "Bel de verkoper",
    "car.sendEmail": "Stuur een email",
    "car.linkCopied": "Link gekopieerd!",
    "car.linkCopiedDesc": "De link is naar het klembord gekopieerd",
    "car.relatedCars": "Vergelijkbare voertuigen",
    "car.location": "Locatie",
    "car.disclaimer": "AutoRa is geen betalingsintermediair. Betaal nooit voordat u het voertuig heeft gezien.",
    
    // Auth
    "auth.login": "Inloggen",
    "auth.signup": "Account aanmaken",
    "auth.loginSubtitle": "Log in om toegang te krijgen tot uw ruimte",
    "auth.signupSubtitle": "Registreer om te beginnen",
    "auth.continueGoogle": "Doorgaan met Google",
    "auth.or": "of",
    "auth.fullName": "Volledige naam",
    "auth.email": "E-mailadres",
    "auth.password": "Wachtwoord",
    "auth.submit": "Inloggen",
    "auth.submitSignup": "Registreren",
    "auth.loading": "Laden...",
    "auth.noAccount": "Nog geen account?",
    "auth.hasAccount": "Al een account?",
    "auth.backHome": "Terug naar home",
    "auth.findIdealCar": "Vind uw ideale auto",
    "auth.heroDesc": "Duizenden geverifieerde voertuigen met Car-Pass en gegarandeerde LEZ-compatibiliteit op de Belgische markt.",
    "auth.errorLogin": "Inlogfout",
    "auth.errorCredentials": "E-mail of wachtwoord onjuist",
    "auth.welcome": "Welkom!",
    "auth.loginSuccess": "Succesvol ingelogd",
    "auth.accountExists": "Account bestaat",
    "auth.accountExistsDesc": "Er bestaat al een account met dit e-mailadres",
    "auth.accountCreated": "Account aangemaakt!",
    "auth.accountCreatedDesc": "Uw account is succesvol aangemaakt",
    "auth.error": "Fout",
    "auth.unexpectedError": "Er is een onverwachte fout opgetreden",
    "auth.invalidEmail": "Ongeldig e-mailadres",
    "auth.passwordMin": "Het wachtwoord moet minimaal 6 tekens bevatten",
    "auth.passwordMinStrong": "Het wachtwoord moet minimaal 8 tekens bevatten",
    "auth.passwordUppercase": "Het wachtwoord moet minimaal één hoofdletter bevatten",
    "auth.passwordLowercase": "Het wachtwoord moet minimaal één kleine letter bevatten",
    "auth.passwordNumber": "Het wachtwoord moet minimaal één cijfer bevatten",
    "auth.passwordSpecial": "Het wachtwoord moet minimaal één speciaal teken bevatten",
    "auth.nameMin": "De naam moet minimaal 2 tekens bevatten",
    "auth.forgotPassword": "Wachtwoord vergeten",
    "auth.forgotPasswordDesc": "Voer uw e-mailadres in en wij sturen u een link om uw wachtwoord te resetten.",
    "auth.forgotPasswordLink": "Wachtwoord vergeten?",
    "auth.sendResetLink": "Link versturen",
    "auth.resetEmailSent": "E-mail verzonden!",
    "auth.resetEmailSentDesc": "Controleer uw inbox om uw wachtwoord te resetten.",
    "auth.backToLogin": "Terug naar inloggen",
    "auth.newPassword": "Nieuw wachtwoord",
    "auth.newPasswordDesc": "Kies een nieuw veilig wachtwoord voor uw account.",
    "auth.newPasswordPlaceholder": "Nieuw wachtwoord",
    "auth.confirmPasswordPlaceholder": "Bevestig wachtwoord",
    "auth.passwordsNotMatch": "Wachtwoorden komen niet overeen",
    "auth.resetPasswordSubmit": "Wachtwoord resetten",
    "auth.passwordResetSuccess": "Wachtwoord gereset!",
    "auth.passwordResetSuccessDesc": "Uw wachtwoord is succesvol gewijzigd.",
    "auth.goToHome": "Naar startpagina",
    "auth.resetLinkExpired": "De resetlink is verlopen of ongeldig.",
    "auth.verificationEmailSent": "Controleer uw e-mail",
    "auth.verificationEmailSentDesc": "We hebben een verificatie-e-mail naar uw adres gestuurd. Klik op de link om uw account te activeren.",
    "auth.checkSpam": "Controleer ook uw spam-map als u de e-mail niet kunt vinden.",
    "auth.emailNotVerified": "E-mail niet geverifieerd",
    "auth.emailNotVerifiedDesc": "Verifieer uw e-mail voordat u inlogt.",
    "auth.resendEmail": "Verificatie-e-mail opnieuw verzenden",
    "auth.resendSuccess": "E-mail verzonden!",
    "auth.resendSuccessDesc": "Er is een nieuwe verificatie-e-mail verzonden.",
    
    // Sell Car
    "sell.title": "Verkoop uw auto",
    "sell.editTitle": "Wijzig uw advertentie",
    "sell.subtitle": "Plaats uw advertentie in enkele minuten en bereik duizenden kopers in België",
    "sell.editSubtitle": "Werk de informatie van uw voertuig bij",
    "sell.loginToSell": "Log in om te verkopen",
    "sell.loginDesc": "Maak een gratis account aan om uw advertentie te plaatsen en uw voertuigen te beheren.",
    "sell.secureListings": "Beveiligde advertenties",
    "sell.quickPublish": "Snelle publicatie",
    "sell.carpassVerification": "Car-Pass verificatie",
    "sell.loginSignup": "Inloggen / Registreren",
    
    // FAQ
    "faq.helpCenter": "Helpcentrum",
    "faq.title": "Veelgestelde vragen",
    "faq.subtitle": "Vind snel antwoorden op uw vragen over AutoRa, de Car-Pass, LEZ-zones en meer.",
    "faq.searchPlaceholder": "Zoek een vraag...",
    "faq.all": "Alle",
    "faq.account": "Account",
    "faq.purchase": "Aankoop",
    "faq.sale": "Verkoop",
    "faq.security": "Beveiliging",
    "faq.payment": "Betaling",
    "faq.noResults": "Geen vragen komen overeen met uw zoekopdracht.",
    "faq.resultsFor": "resultaten gevonden",
    "faq.resultFor": "resultaat gevonden",
    "faq.noResult": "Geen resultaten",
    "faq.for": "voor",
    "faq.in": "in",
    "faq.notFound": "Uw antwoord niet gevonden?",
    "faq.notFoundDesc": "Ons team staat voor u klaar. Neem contact met ons op via contact@autora.be",
    "faq.contactUs": "Neem contact op",
    "faq.linkCopied": "Link gekopieerd!",
    
    // Footer
    "footer.description": "De betrouwbare Belgische automarktplaats. Al onze voertuigen zijn geverifieerd met Car-Pass.",
    "footer.navigation": "Navigatie",
    "footer.buyCar": "Een auto kopen",
    "footer.sellCar": "Mijn auto verkopen",
    "footer.estimate": "Mijn voertuig schatten",
    "footer.lezGuide": "LEZ-gids België",
    "footer.info": "Informatie",
    "footer.about": "Over ons",
    "footer.carpass": "Car-Pass België",
    "footer.terms": "Algemene voorwaarden",
    "footer.privacy": "Privacybeleid",
    "footer.legal": "Wettelijke vermeldingen",
    "footer.contact": "Contact",
    "footer.rights": "Alle rechten voorbehouden.",
    "footer.madeWith": "Gemaakt met ❤️ in België",
    
    // Messages
    "messages.title": "Berichten",
    "messages.noMessages": "Geen berichten",
    "messages.noMessagesDesc": "U heeft nog geen gesprekken. Neem contact op met een verkoper om te beginnen.",
    "messages.viewVehicles": "Bekijk voertuigen",
    "messages.conversations": "Gesprekken",
    "messages.noMessage": "Geen bericht",
    "messages.selectConversation": "Selecteer een gesprek",
    "messages.yesterday": "Gisteren",
    
    // Settings
    "settings.title": "Instellingen",
    "settings.back": "Terug",
    "settings.notifications": "Meldingen",
    "settings.notificationsDesc": "Beheer uw meldingsvoorkeuren",
    "settings.emailNotifications": "E-mailmeldingen",
    "settings.emailNotificationsDesc": "Ontvang een e-mail wanneer een koper u een bericht stuurt",
    "settings.emailEnabled": "E-mailmeldingen ingeschakeld",
    "settings.emailDisabled": "E-mailmeldingen uitgeschakeld",
    "settings.errorUpdate": "Fout bij het bijwerken van voorkeuren",
    "settings.account": "Account",
    "settings.accountDesc": "Uw accountgegevens",
    "settings.email": "E-mail",
    
    // Dashboard
    "dashboard.sellerArea": "Verkopersruimte",
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Volg de prestaties van uw advertenties",
    "dashboard.exportCSV": "Exporteer CSV",
    "dashboard.listings": "Advertenties",
    "dashboard.totalViews": "Totale weergaven",
    "dashboard.messages": "Berichten",
    "dashboard.favorites": "Favorieten",
    "dashboard.globalPerformance": "Globale prestaties",
    "dashboard.noDataAvailable": "Geen gegevens beschikbaar",
    "dashboard.detailByListing": "Detail per advertentie",
    "dashboard.noListingsYet": "U heeft nog geen advertenties",
    "dashboard.createListing": "Maak een advertentie",
    "dashboard.views": "Weergaven",
    "dashboard.published": "Gepubliceerd",
    "dashboard.pending": "In afwachting",
    "dashboard.rejected": "Geweigerd",
    "dashboard.deleteListing": "Deze advertentie verwijderen?",
    "dashboard.deleteConfirm": "Weet u zeker dat u de advertentie wilt verwijderen voor",
    "dashboard.deleteIrreversible": "Deze actie is onomkeerbaar.",
    "dashboard.cancel": "Annuleren",
    "dashboard.delete": "Verwijderen",
    "dashboard.deleting": "Verwijderen...",
    "dashboard.deleteSuccess": "Advertentie succesvol verwijderd",
    "dashboard.deleteError": "Fout bij het verwijderen",
    "dashboard.csvDownloaded": "CSV-export gedownload",
    "dashboard.vehicle": "Voertuig",
    "dashboard.status": "Status",
    "dashboard.price": "Prijs",
    "dashboard.createdAt": "Aanmaakdatum",
    "dashboard.total": "TOTAAL",
  },
  en: {
    // Navigation
    "nav.buy": "Buy",
    "nav.sell": "Sell",
    "nav.favorites": "Favorites",
    "nav.compare": "Compare",
    "nav.messages": "Messages",
    "nav.dashboard": "Dashboard",
    "nav.settings": "Settings",
    "nav.faq": "FAQ",
    "nav.login": "Login",
    "nav.logout": "Logout",
    "theme.light": "Light mode",
    "theme.dark": "Dark mode",
    "logout.success": "Logged out",
    "logout.description": "You have been logged out successfully",
    
    // Hero
    "hero.badge": "Belgian car market",
    "hero.title1": "Find your next",
    "hero.title2": "car in Belgium",
    "hero.subtitle": "Thousands of verified vehicles, with Car-Pass and guaranteed LEZ compatibility",
    "hero.search": "Search",
    "hero.vehicles": "Vehicles",
    "hero.verified": "Car-Pass verified",
    "hero.brands": "Brands",
    
    // Filters
    "filters.title": "Filters",
    "filters.vehicles": "vehicles",
    "filters.brand": "Brand",
    "filters.allBrands": "All brands",
    "filters.model": "Model",
    "filters.budget": "Budget",
    "filters.year": "Year",
    "filters.mileage": "Mileage",
    "filters.fuel": "Fuel",
    "filters.transmission": "Transmission",
    "filters.euroNorm": "Euro Standard (LEZ)",
    "filters.lezOnly": "LEZ compatible only",
    "filters.reset": "Reset filters",
    "filters.gasoline": "Gasoline",
    "filters.diesel": "Diesel",
    "filters.hybrid": "Hybrid",
    "filters.electric": "Electric",
    "filters.manual": "Manual",
    "filters.automatic": "Automatic",
    
    // Car Card & Detail
    "car.addCompare": "Add to compare",
    "car.removeCompare": "Remove from compare",
    "car.addedCompare": "Added to compare",
    "car.removedCompare": "Removed from compare",
    "car.maxCompare": "Maximum 3 vehicles in compare",
    "car.notFound": "Vehicle not found",
    "car.notFoundDesc": "This vehicle does not exist or has been removed from sale.",
    "car.backToListings": "Back to listings",
    "car.backToResults": "Back to results",
    "car.specifications": "Specifications",
    "car.description": "Description",
    "car.sendMessage": "Send a message",
    "car.callSeller": "Call the seller",
    "car.sendEmail": "Send an email",
    "car.linkCopied": "Link copied!",
    "car.linkCopiedDesc": "The link has been copied to clipboard",
    "car.relatedCars": "Similar vehicles",
    "car.location": "Location",
    "car.disclaimer": "AutoRa is not a payment intermediary. Never pay before seeing the vehicle.",
    
    // Auth
    "auth.login": "Login",
    "auth.signup": "Create account",
    "auth.loginSubtitle": "Login to access your space",
    "auth.signupSubtitle": "Sign up to get started",
    "auth.continueGoogle": "Continue with Google",
    "auth.or": "or",
    "auth.fullName": "Full name",
    "auth.email": "Email address",
    "auth.password": "Password",
    "auth.submit": "Login",
    "auth.submitSignup": "Sign up",
    "auth.loading": "Loading...",
    "auth.noAccount": "No account yet?",
    "auth.hasAccount": "Already have an account?",
    "auth.backHome": "Back to home",
    "auth.findIdealCar": "Find your ideal car",
    "auth.heroDesc": "Thousands of verified vehicles with Car-Pass and guaranteed LEZ compatibility on the Belgian market.",
    "auth.errorLogin": "Login error",
    "auth.errorCredentials": "Incorrect email or password",
    "auth.welcome": "Welcome!",
    "auth.loginSuccess": "Successfully logged in",
    "auth.accountExists": "Account exists",
    "auth.accountExistsDesc": "An account already exists with this email address",
    "auth.accountCreated": "Account created!",
    "auth.accountCreatedDesc": "Your account has been created successfully",
    "auth.error": "Error",
    "auth.unexpectedError": "An unexpected error occurred",
    "auth.invalidEmail": "Invalid email address",
    "auth.passwordMin": "Password must be at least 6 characters",
    "auth.passwordMinStrong": "Password must be at least 8 characters",
    "auth.passwordUppercase": "Password must contain at least one uppercase letter",
    "auth.passwordLowercase": "Password must contain at least one lowercase letter",
    "auth.passwordNumber": "Password must contain at least one number",
    "auth.passwordSpecial": "Password must contain at least one special character",
    "auth.nameMin": "Name must be at least 2 characters",
    "auth.forgotPassword": "Forgot password",
    "auth.forgotPasswordDesc": "Enter your email address and we'll send you a link to reset your password.",
    "auth.forgotPasswordLink": "Forgot password?",
    "auth.sendResetLink": "Send reset link",
    "auth.resetEmailSent": "Email sent!",
    "auth.resetEmailSentDesc": "Check your inbox to reset your password.",
    "auth.backToLogin": "Back to login",
    "auth.newPassword": "New password",
    "auth.newPasswordDesc": "Choose a new secure password for your account.",
    "auth.newPasswordPlaceholder": "New password",
    "auth.confirmPasswordPlaceholder": "Confirm password",
    "auth.passwordsNotMatch": "Passwords do not match",
    "auth.resetPasswordSubmit": "Reset password",
    "auth.passwordResetSuccess": "Password reset!",
    "auth.passwordResetSuccessDesc": "Your password has been successfully changed.",
    "auth.goToHome": "Go to home",
    "auth.resetLinkExpired": "The reset link has expired or is invalid.",
    "auth.verificationEmailSent": "Check your email",
    "auth.verificationEmailSentDesc": "We've sent a verification email to your address. Click the link to activate your account.",
    "auth.checkSpam": "Also check your spam folder if you can't find the email.",
    "auth.emailNotVerified": "Email not verified",
    "auth.emailNotVerifiedDesc": "Please verify your email before logging in.",
    "auth.resendEmail": "Resend verification email",
    "auth.resendSuccess": "Email sent!",
    "auth.resendSuccessDesc": "A new verification email has been sent.",
    
    // Sell Car
    "sell.title": "Sell your car",
    "sell.editTitle": "Edit your listing",
    "sell.subtitle": "Publish your listing in minutes and reach thousands of buyers in Belgium",
    "sell.editSubtitle": "Update your vehicle information",
    "sell.loginToSell": "Login to sell",
    "sell.loginDesc": "Create a free account to publish your listing and manage your vehicles.",
    "sell.secureListings": "Secure listings",
    "sell.quickPublish": "Quick publishing",
    "sell.carpassVerification": "Car-Pass verification",
    "sell.loginSignup": "Login / Sign up",
    
    // FAQ
    "faq.helpCenter": "Help Center",
    "faq.title": "Frequently Asked Questions",
    "faq.subtitle": "Quickly find answers to your questions about AutoRa, Car-Pass, LEZ zones and more.",
    "faq.searchPlaceholder": "Search a question...",
    "faq.all": "All",
    "faq.account": "Account",
    "faq.purchase": "Purchase",
    "faq.sale": "Sale",
    "faq.security": "Security",
    "faq.payment": "Payment",
    "faq.noResults": "No questions match your search.",
    "faq.resultsFor": "results found",
    "faq.resultFor": "result found",
    "faq.noResult": "No results",
    "faq.for": "for",
    "faq.in": "in",
    "faq.notFound": "Did not find your answer?",
    "faq.notFoundDesc": "Our team is here to help. Contact us at contact@autora.be",
    "faq.contactUs": "Contact us",
    "faq.linkCopied": "Link copied!",
    
    // Footer
    "footer.description": "The trusted Belgian car marketplace. All our vehicles are verified with Car-Pass.",
    "footer.navigation": "Navigation",
    "footer.buyCar": "Buy a car",
    "footer.sellCar": "Sell my car",
    "footer.estimate": "Estimate my vehicle",
    "footer.lezGuide": "LEZ Guide Belgium",
    "footer.info": "Information",
    "footer.about": "About us",
    "footer.carpass": "Car-Pass Belgium",
    "footer.terms": "Terms & Conditions",
    "footer.privacy": "Privacy Policy",
    "footer.legal": "Legal Notice",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved.",
    "footer.madeWith": "Made with ❤️ in Belgium",
    
    // Messages
    "messages.title": "Messages",
    "messages.noMessages": "No messages",
    "messages.noMessagesDesc": "You don't have any conversations yet. Contact a seller to get started.",
    "messages.viewVehicles": "View vehicles",
    "messages.conversations": "Conversations",
    "messages.noMessage": "No message",
    "messages.selectConversation": "Select a conversation",
    "messages.yesterday": "Yesterday",
    
    // Settings
    "settings.title": "Settings",
    "settings.back": "Back",
    "settings.notifications": "Notifications",
    "settings.notificationsDesc": "Manage your notification preferences",
    "settings.emailNotifications": "Email notifications",
    "settings.emailNotificationsDesc": "Receive an email when a buyer sends you a message",
    "settings.emailEnabled": "Email notifications enabled",
    "settings.emailDisabled": "Email notifications disabled",
    "settings.errorUpdate": "Error updating preferences",
    "settings.account": "Account",
    "settings.accountDesc": "Your account information",
    "settings.email": "Email",
    
    // Dashboard
    "dashboard.sellerArea": "Seller area",
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Track the performance of your listings",
    "dashboard.exportCSV": "Export CSV",
    "dashboard.listings": "Listings",
    "dashboard.totalViews": "Total views",
    "dashboard.messages": "Messages",
    "dashboard.favorites": "Favorites",
    "dashboard.globalPerformance": "Global performance",
    "dashboard.noDataAvailable": "No data available",
    "dashboard.detailByListing": "Detail by listing",
    "dashboard.noListingsYet": "You don't have any listings yet",
    "dashboard.createListing": "Create a listing",
    "dashboard.views": "Views",
    "dashboard.published": "Published",
    "dashboard.pending": "Pending",
    "dashboard.rejected": "Rejected",
    "dashboard.deleteListing": "Delete this listing?",
    "dashboard.deleteConfirm": "Are you sure you want to delete the listing for",
    "dashboard.deleteIrreversible": "This action is irreversible.",
    "dashboard.cancel": "Cancel",
    "dashboard.delete": "Delete",
    "dashboard.deleting": "Deleting...",
    "dashboard.deleteSuccess": "Listing deleted successfully",
    "dashboard.deleteError": "Error deleting listing",
    "dashboard.csvDownloaded": "CSV export downloaded",
    "dashboard.vehicle": "Vehicle",
    "dashboard.status": "Status",
    "dashboard.price": "Price",
    "dashboard.createdAt": "Created at",
    "dashboard.total": "TOTAL",
  },
};

const languageLabels: Record<Language, string> = {
  fr: "FR",
  nl: "NL",
  en: "EN",
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "fr";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export const getLanguageLabel = (lang: Language) => languageLabels[lang];
